pipelines:
  PAYMENT-SERVICE:
    group: payment
    timer:
      only_on_changes: yes
      spec: "* * * * * ?"
    materials:
      mygit:
        git: https://117.121.110.36/daimler-payment/payment-service.git
    stages:
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - sbt
              tasks:
                - exec:
                    command: sbt
                    arguments:
                      - clean
                      - test
                    run_if: passed
      - build:
          clean_workspace: true
          jobs:
            docker:
              resources:
                - docker-img-builder
              tasks:
                - exec:
                    command: sbt
                    arguments:
                      - clean
                      - dist
                    run_if: passed
                - exec:
                    command: unzip
                    arguments:
                      - -o
                      - target/universal/payment-service-*.zip
                    run_if: passed
                - plugin:
                    run_if: passed
                    configuration:
                      id: docker.pipeline.plugin
                      version: 1
                    options:
                      ImageName: payment-service
                      DockerFileName: Dockerfile
                      RegistryUsername: daimlermme
                      RegistryPassword: docker2017!
                      Username: payment
                      RegistryURL: 117.121.110.38:443
                      ImageTag: ${GO_PIPELINE_LABEL};latest
                      isPush: true
                      BUILD_NO_CACHE: true
                      CleanAfterComplete: false
                      BUILD_MICROLABELING: false
  PAYMENT-SERVICE-SONAR:
    group: payment
    timer:
      only_on_changes: yes
      spec: "0 0 6 ? * MON-FRI"
    materials:
      mygit:
        git: https://117.121.110.36/daimler-payment/payment-service.git
    stages:
      - sonar:
          clean_workspace: true
          jobs:
            test:
              resources:
                - sbt
              tasks:
                - exec:
                    command: ./sonar-scanner-2.8/bin/sonar-scanner
                    run_if: passed
